version: "3.9"
services:
  cowsay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cowsay
    # ports:
    #   - "8080:8080"
    networks:
      - cowsay-nginx
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 15s
      retries: 6
      start_period: 10s
      timeout: 10s

  shield:
    container_name: shield
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    image: nginx
    ports:
      - "4000:80"
    networks:
      - cowsay-nginx
    volumes:
      # - type:  bind
      #   source: /home/ubuntu/cowsay/conf/nginx.conf
      #   target: /etc/nginx/nginx.conf
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/access.log:/var/log/nginx/access.log
      # - $PWD/conf/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  cowsay-nginx:


