version: "3.9"
services:
  cowsay:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    networks:
      - cowsay-nginx

  shield:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    image: nginx
    ports:
      - "4000:80"
    networks:
      - cowsay-nginx
    volumes:
      - $PWD/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/conf/access.log:/var/log/nginx/access.log
      # - $PWD/conf/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  cowsay-nginx:
